# Generated by Django 5.1.1 on 2024-09-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_book_alter_user_role_loan_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
