# Generated by Django 5.1.1 on 2024-09-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_book_image_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_borrowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("returned", "Returned")],
                default="open",
                max_length=100,
            ),
        ),
    ]
